#=================================基础配置========================================================
server:
  port: 7165
#=================================数据库配置========================================================
spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 5
    validationQuery: select 'x'
    initialSize: 5
    maxWait: 60000
    poolPreparedStatements: true
    filters: stat,wall,slf4j
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/httpclient?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    platform: mysql
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 300
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#=================================其他配置========================================================
#解决mybaits传入空值问题
mybatis:
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true